[project]
name = "howdoyoufindme"
version = "0.1.0"
description = "howdoyoufindme-backend using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.95.0,<1.0.0"
]

[project.scripts]
howdoyoufindme = "howdoyoufindme.main:run"
run_crew = "howdoyoufindme.main:run"
train = "howdoyoufindme.main:train"
replay = "howdoyoufindme.main:replay"
test = "howdoyoufindme.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
