# src/howdoyoufindme/config/tasks.yaml

generate_keywords_task:
  description: >
    For the company or website '{query}':
    1. Identify their primary industry/category
    2. List their main competitors in this space
    3. Generate keywords that define this market segment
  expected_output: >
    {
      "category": "Industry category",
      "competitors": ["List of main competitors"],
      "keywords": ["List of relevant keywords"]
    }
  agent: keyword_agent

build_query_task:
  description: >
    Use the category and competitor information to:
    1. Create search queries to find industry rankings and market positions
    2. Search for authoritative sources that rank companies in this space
    3. Gather competitive positioning data
  expected_output: >
    {
      "queries": ["List of search queries used"],
      "results": ["List of search results and findings"]
    }
  agent: query_builder_agent
  context: [generate_keywords_task]

ranking_task:
  description: >
    Analyze where '{query}' ranks in their industry:
    1. Review search results for rankings and market position
    2. Compare against identified competitors
    3. Determine their position (e.g., "ranks #5 in online hearing aid providers")
    4. Include context about market leaders and competitive position

    IMPORTANT: Return data in this EXACT format (do not add any other fields):
    {
      "ranking_position": "Company ranks #X in [industry]",
      "market_context": {
        "market_size": "Total market size",
        "growth_projections": "Growth rate"
      },
      "comparison_to_leaders": {
        "top_competitors": [
          {
            "company": "Company name",
            "rank": 1,
            "market_share": "XX%"
          }
        ],
        "summary": "Brief competitive analysis"
      }
    }

    - Use numbers for ranks (not strings)
    - Keep market share as percentage strings
    - Do not add extra fields
    - Format exactly as shown above
  expected_output: >
    A JSON object with ranking position, market context, and competitor comparison
  agent: ranking_agent
  context: [build_query_task]