# src/howdoyoufindme/config/tasks.yaml

generate_keywords_task:
  description: >
    For the company or website '{query}':
    1. Identify their primary industry/category
    2. List their main competitors in this space
    3. Generate keywords that define this market segment
  expected_output: >
    {
      "category": "Industry category",
      "competitors": ["List of main competitors"],
      "keywords": ["List of relevant keywords"]
    }
  agent: keyword_agent

build_query_task:
  description: >
    Use the category and competitor information to:
    1. Create search queries to find industry rankings and market positions
    2. Search for authoritative sources that rank companies in this space
    3. Gather competitive positioning data
  expected_output: >
    {
      "queries": ["List of search queries used"],
      "results": ["List of search results and findings"]
    }
  agent: query_builder_agent
  context: [generate_keywords_task]

ranking_task:
  description: >
    Analyze where '{query}' ranks in their industry:
    1. Review search results for rankings and market position
    2. Compare against identified competitors
    3. Determine their position (e.g., "ranks #5 in online hearing aid providers")
    4. Include context about market leaders and competitive position
  expected_output: >
    {
      "ranking_position": "Clear ranking statement",
      "market_context": {
        "market_size": "Total market size",
        "growth_projections": "Growth projections"
      },
      "comparison_to_leaders": {
        "top_competitors": [
          {
            "company": "Competitor name",
            "rank": "Numeric rank",
            "market_share": "Market share percentage"
          }
        ],
        "summary": "Competitive analysis summary"
      }
    }
  agent: ranking_agent
  context: [build_query_task]