# src/howdoyoufindme/config/tasks.yaml
generate_keywords_task:
  description: >
    For the company '{query}':
    1. Identify their primary industry/category
    2. List their main competitors in this space
    3. Generate keywords that define this market segment
    Format output as dictionary with 'category', 'competitors', and 'keywords' keys.
  expected_output: >
    Dictionary containing industry category, main competitors, and relevant keywords
  agent: keyword_agent

build_query_task:
  description: >
    Using the category and competitor information:
    1. Create search queries to find industry rankings and market positions
    2. Search for authoritative sources that rank companies in this space
    3. Gather competitive positioning data
    Return both the queries used and the search results.
  expected_output: >
    Dictionary with search queries and results focusing on industry rankings
  agent: query_builder_agent
  context:
    - generate_keywords_task

ranking_task:
  description: >
    Analyze where '{query}' ranks in their industry:
    1. Review search results for rankings and market position
    2. Compare against identified competitors
    3. Determine their position (e.g., "ranks #5 in online hearing aid providers")
    4. Include context about market leaders and competitive position
  expected_output: >
    Dictionary with ranking position, market context, and comparison to leaders
  agent: ranking_agent
  context:
    - build_query_task