generate_keywords_task:
  description: >
    Analyze the company/brand/product name '{query}' and generate:
    1. A list of 5-10 relevant keywords
    2. A comprehensive description (2-3 sentences)
  expected_output: >
    A dictionary with 'keywords' and 'description' keys
  agent: keyword_agent

build_query_task:
  description: >
    Using the keywords and description provided:
    1. Create an optimized Bing search query
    2. Execute the search using the Bing Search API
  expected_output: >
    Dictionary containing search query and raw results
  agent: query_builder_agent
  context:
    - generate_keywords_task

ranking_task:
  description: >
    Analyze the search results for '{query}':
    1. Find mentions of the target company/brand/product
    2. Score each result based on relevance (0-100)
    3. Generate a ranked list of the top matches
  expected_output: >
    List of dictionaries with 'title' and 'score' keys
  agent: ranking_agent
  context:
    - build_query_task